### ISSUE TITLE
Clean implementation of D2Q21 update loop

### ISSUE THREAD

**Issue by uschille** [niktre/mlb_jasna#1]
I think this can be done along  the lines of my D3Q19 implementation at https://gist.github.com/uschille/8f65dd40572b2d943409.

**Comment by uschille** [comment]
@niktre: Few questions came up here:
- [x] Will we need BGK or MRT?
- [x] Will periodic boundary conditions suffice?
- [x] Should it be a fluctuating D2Q21?

**Comment by niktre** [comment]
1. There is an algorithm written by Burkhard, that is coupled onto BGK. I believe it is much easier to make MRT->BGK transition in the code than BGK->MRT in theory (however, it is totally possible). The algorithm is a supplementary material to the paper, I'll send it to you. 
2. PBC are enough. 
3. Fluctuations are not needed. The work with fluctuations may constitute to another paper, by the way.

**Comment by niktre** [comment]
Here is what Burkhard wrote himself.

Am 18.07.15 um 18:56 schrieb Ulf Schiller:
>
> Few questions came up here:
>
>   * Will we need BGK or MRT?
>   * Will periodic boundary conditions suffice?
>   * Should it be a fluctuating D2Q21?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/niktre/mlb_jasna/issues/1#issuecomment-122563774>.
>

-- 
Dr. Nikita Tretyakov (Polymer Theory Group)
Max Planck Institute for Polymer Research
Ackermannweg 10
55128 Mainz, Germany
Tel. +49-6131-379-473

**Comment by niktre** [comment]
I've taken a look on your program. It is indeed much easier to derive multiphase D2Q21 from there. Can we split the work somehow?

**Comment by uschille** [comment]
Thanks for the supplemental info. I think it will be relatively easy to implement D2Q21 with PBC. I'll do a standard BGK first which I've started on my fork a381b94956c8ec05728aac4a07cd51868df2687b, feel free to pull updates as I pootle along.

**Comment by uschille** [comment]
9023748a79348302aba91d6773213c88c9873782 might be the first runnable version and needs to be tested now.

**Comment by uschille** [comment]
Of course it's not really multiphase yet... just a D2Q21 LBGK...

**Comment by uschille** [comment]
I think as a single phase implementation this is now basically working, so I'm closing #1 now. Feel free to re-open if any issues remain.
