### ISSUE TITLE
Implicit algorithm

### ISSUE THREAD

**Issue by uschille** [niktre/mlb_jasna#13]
In Burkhard's supplemental material, I am wondering whether one can join step 4 and step 5 by inserting Eq. (7) into Eq. (8) and using the chain rule. The result could be evaluated in one loop over the lattice which seems more efficient.

Some notes for myself for later reference...
- [x] Check if pbc_y need to be adjusted
- [x] Check if HALO size can be reduced again

**Comment by niktre** [comment]
I need a bit of time to think about it

**Comment by uschille** [comment]
I will implement an "inefficient" naive algorithm first. I have ideas how things can be improved by calculating the interface force on the fly in the main loop, but this is a bit more complicated. I would like to see if it works first...

**Comment by uschille** [comment]
Implemented a simple Gauss-Seidel iteration in 8459a1436d18b47f12b99c842d64c80b9f73d6c5. Strangely it produces different currents than the naive algorithm. Time for some debugging.

**Comment by uschille** [comment]
Implemented MINRES now, hower it does not always seem to converge and produces solutions different from both Gauss-Seidel and the naive iteration.

**Comment by uschille** [comment]
The implementation may not be the full MINRES method after all. I was naively trusting https://de.wikipedia.org/wiki/MINRES-Verfahren

**Comment by uschille** [comment]
Added an interface to the Fortran 90 implementation at http://web.stanford.edu/group/SOL/software/minres/. This implementation could serve as a reference. The interface needs testing though.

**Comment by uschille** [comment]
I think the interface to the Fortran subroutine is now working. However, when called from the multiphase LB it reports that the matrix is not symmetric. I'll need to check whether it actually should be symmetric (I've trusted BD on this one).

**Comment by uschille** [comment]
After a fix of the Gauss-Seidel method in 7f00218, finally there seems to be agreement between the naive algorithm, Gauss-Seidel, and GMRES.
