### ISSUE TITLE
Question on derivation in Appendix C

### ISSUE THREAD

**Issue by uschille** [niktre/mlb_jasna#17]
In Eq. (C4) how do I get from the third line to the fourth?

**Comment by uschille** [comment]
Got it!

**Comment by niktre** [comment]
I've just read your question and started to do math.. It is a combi of 
A4 and continuity equation?

Am 28.07.15 um 22:42 schrieb Ulf Schiller:

> Got it!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/niktre/mlb_jasna/issues/17#issuecomment-125748363.

## 

Dr. Nikita Tretyakov (Polymer Theory Group)
Max Planck Institute for Polymer Research
Ackermannweg 10
55128 Mainz, Germany
Tel. +49-6131-379-473

**Comment by uschille** [comment]
Yea, I got confused by the D/Dt notation which has not D\rho/Dt=0. Must have been low on blood sugar, after a bar of chocolate everything works out :+1:
