### ISSUE TITLE
Preparation of derivatives

### ISSUE THREAD

**Issue by niktre** [niktre/mlb_jasna#8]
Ulf, I'm about to code the derivatives, however do not understand the following:

in the lb_stream you use for the neighborhood :
  xc = x%WGRID;
  xp  = (x+1)%WGRID; xm  = (x-1+WGRID)%WGRID;
  xp2 = (x+2)%WGRID; xm2 = (x-2+WGRID)%WGRID;
  xp4 = (x+4)%WGRID; xm4 = (x-4+WGRID)%WGRID;

It gives you a stripe of 9 points, you then label them as (from left to right) 5,6,7,8,0,1,2,3,4. Is it done to get rid of the 5,6,7,8 after streaming?

Should be derivatives calculated in a similar fashion?

**Comment by uschille** [comment]
> It gives you a stripe of 9 points, you then label them as (from left to right) 5,6,7,8,0,1,2,3,4. Is it done to get rid of the 5,6,7,8 after streaming?

This only applies to the temporary array that is used to prevent premature overwriting of data. It is kind of a circular buffer, in the sense that while iterating over x different indices are used to store the populations, and it contains populations that originate from different columns. Basically the centre of the 9 stripes rotates along while walking over the grid, hence I call it a _walking grid_. **This temporary grid does not contain the hydrodynamic moments, so it can not be used for the derivatives.**

> Should be derivatives calculated in a similar fashion?

I think the derivatives have to be calculated from the array `lbf` where also the hydrodynamic moments are stored. I have to think about a convenient way of accessing non-local indices as the pointer is incremented while iterating over lattice sites, so the correct offsets have to be used to find the neighbours.

**Comment by uschille** [comment]
I have now added some prerequisites for the derivatives. I had a quick try at the interface force as well.

**Comment by niktre** [comment]
Could you help me in understanding the memory allocation? At first, `lblattice.halo_grid_volume*lbmodel.n_vel` doubles are used for populations of the halo and real regions, then 19 moments are stored for the nodes of the real region?

What is `nb_offset`?

**Comment by uschille** [comment]
In the array `lbf` there are first the `lblattice.halo_grid_volume*lbmodel.n_vel` populations for the entire lattice including halo, and after that the hydrodynamic moments. In principle there are `lbmodel.n_vel` moments in memory for each lattice site but only the first six are calculated in `static void lb_calc_modes(double *f)`.

If you have a pointer `double *f` that points to a lattice site, then `f[0]`...`f[20]` are the populations for that site. The moments for this site start at `(f + lblattice.halo_grid_volume*lbmodel.n_vel)`.

The array `nb_offset[21]` can be used to look at neighbouring sites. So, if you have `m = (f + lblattice.halo_grid_volume*lbmodel.n_vel)` then `m[0]` is the density at the site, and `m[nb_offset[i]*lbmodel.n_vel]` is the density at the neighbour in direction `c[i]`.

I admit this may look a bit obscure at first, and an array of structs for the moments might be more readable. However, when one does MRT then there are no good names for the ghost modes and one would end up having entries like `ghost1`, `ghost2` in the struct, and it would not be possible to index the moments.
